package com.jingao.cn.mapper.permission;

import com.jingao.cn.entity.permission.PermissionTree;
import com.jingao.cn.entity.permission.PermissionTreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Sun Dec 10 16:25:07 CST 2017
     */
    int countByExample(PermissionTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Sun Dec 10 16:25:07 CST 2017
     */
    int deleteByExample(PermissionTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Sun Dec 10 16:25:07 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Sun Dec 10 16:25:07 CST 2017
     */
    int insert(PermissionTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Sun Dec 10 16:25:07 CST 2017
     */
    int insertSelective(PermissionTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Sun Dec 10 16:25:07 CST 2017
     */
    List<PermissionTree> selectByExample(PermissionTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Sun Dec 10 16:25:07 CST 2017
     */
    PermissionTree selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Sun Dec 10 16:25:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") PermissionTree record, @Param("example") PermissionTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Sun Dec 10 16:25:07 CST 2017
     */
    int updateByExample(@Param("record") PermissionTree record, @Param("example") PermissionTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Sun Dec 10 16:25:07 CST 2017
     */
    int updateByPrimaryKeySelective(PermissionTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Sun Dec 10 16:25:07 CST 2017
     */
    int updateByPrimaryKey(PermissionTree record);
}