package com.jingao.cn.mapper.permission;

import com.jingao.cn.entity.permission.PermissionDic;
import com.jingao.cn.entity.permission.PermissionDicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_DIC
     *
     * @mbggenerated Wed Dec 06 16:59:55 CST 2017
     */
    int countByExample(PermissionDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_DIC
     *
     * @mbggenerated Wed Dec 06 16:59:55 CST 2017
     */
    int deleteByExample(PermissionDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_DIC
     *
     * @mbggenerated Wed Dec 06 16:59:55 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_DIC
     *
     * @mbggenerated Wed Dec 06 16:59:55 CST 2017
     */
    int insert(PermissionDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_DIC
     *
     * @mbggenerated Wed Dec 06 16:59:55 CST 2017
     */
    int insertSelective(PermissionDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_DIC
     *
     * @mbggenerated Wed Dec 06 16:59:55 CST 2017
     */
    List<PermissionDic> selectByExample(PermissionDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_DIC
     *
     * @mbggenerated Wed Dec 06 16:59:55 CST 2017
     */
    PermissionDic selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_DIC
     *
     * @mbggenerated Wed Dec 06 16:59:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") PermissionDic record, @Param("example") PermissionDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_DIC
     *
     * @mbggenerated Wed Dec 06 16:59:55 CST 2017
     */
    int updateByExample(@Param("record") PermissionDic record, @Param("example") PermissionDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_DIC
     *
     * @mbggenerated Wed Dec 06 16:59:55 CST 2017
     */
    int updateByPrimaryKeySelective(PermissionDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION_DIC
     *
     * @mbggenerated Wed Dec 06 16:59:55 CST 2017
     */
    int updateByPrimaryKey(PermissionDic record);
}