spring:
  profiles:
    active: dev
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: likun
    password: 123456
    initialSize: 1
    minIdle: 1
    maxIdle: 20
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    testWhileIdle: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  #thymeleaf模板引擎
  thymeleaf:
      encoding: utf-8
      content-type: text/html
      mode: HTML5
  resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**


  redis:
    host: localhost
    port: 6379
    database: 1
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 500
      min-idle: 0

  session:
    store-type: redis

#mybatis
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
#  type-aliases-package: exampleProjectRepository.**.entity
#mybatis分页插件
pagehelper:
  helper-dialect: oracle
  offset-as-page-num: true
  row-bounds-with-count: true
#logging:
#  file: ./logs/app_log.log
