package com.jingao.cn.entity.user;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.ID
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.NAME
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.ID_NUM
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    private String idNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.PWD
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.PHONE_NUM
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    private String phoneNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.ID
     *
     * @return the value of USERS.ID
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.ID
     *
     * @param id the value for USERS.ID
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.NAME
     *
     * @return the value of USERS.NAME
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.NAME
     *
     * @param name the value for USERS.NAME
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.ID_NUM
     *
     * @return the value of USERS.ID_NUM
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.ID_NUM
     *
     * @param idNum the value for USERS.ID_NUM
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.PWD
     *
     * @return the value of USERS.PWD
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.PWD
     *
     * @param pwd the value for USERS.PWD
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.PHONE_NUM
     *
     * @return the value of USERS.PHONE_NUM
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.PHONE_NUM
     *
     * @param phoneNum the value for USERS.PHONE_NUM
     *
     * @mbggenerated Tue Sep 26 17:12:28 CST 2017
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }
}