package com.jingao.cn.entity.permission;

public class PermissionDic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION_DIC.ID
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION_DIC.NAME
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION_DIC.TITLE
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION_DIC.PID
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION_DIC.VALUE
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION_DIC.ID
     *
     * @return the value of PERMISSION_DIC.ID
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION_DIC.ID
     *
     * @param id the value for PERMISSION_DIC.ID
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION_DIC.NAME
     *
     * @return the value of PERMISSION_DIC.NAME
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION_DIC.NAME
     *
     * @param name the value for PERMISSION_DIC.NAME
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION_DIC.TITLE
     *
     * @return the value of PERMISSION_DIC.TITLE
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION_DIC.TITLE
     *
     * @param title the value for PERMISSION_DIC.TITLE
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION_DIC.PID
     *
     * @return the value of PERMISSION_DIC.PID
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION_DIC.PID
     *
     * @param pid the value for PERMISSION_DIC.PID
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION_DIC.VALUE
     *
     * @return the value of PERMISSION_DIC.VALUE
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION_DIC.VALUE
     *
     * @param value the value for PERMISSION_DIC.VALUE
     *
     * @mbggenerated Thu Dec 07 10:39:39 CST 2017
     */
    public void setValue(String value) {
        this.value = value;
    }
}